service: img-similar-lambda-docker

provider:
  name: aws # provider
  region: ap-northeast-2 # aws region
  memorySize: 5120 # optional, in MB, default is 1024
  timeout: 30 # optional, in seconds, default is 6
 
functions:
  sim-imgs:
    image: 479234898386.dkr.ecr.ap-northeast-2.amazonaws.com/get-sim-imgs:latest
    events:
      - http:
          path: sm # http path
          method: post # http method

